### ISSUE TITLE
cut-off implementation performance with medical schemes

### ISSUE THREAD

**Issue by Ahmed-Naceur** [Ahmed-Naceur/dragon5#11]
For CEPXS-BFP Medical schemes, I did a specific follow-up. This is the current situation:

- Working for:
TCM64.c2m
TCM65.c2m
TCM66.c2m 

- Not Working for:
TCM67 ;

- Working for:
TCM68 ;
TCM69 ;
TCM70 ;﻿

**Comment by CBienvenue** [comment]
I don't have this situation in my local branch, I will push it soon.
